### PR TITLE
Enable SOAP

### PR DESCRIPTION
**Pull request by jsamouh**
issue #283 

enabled soap by default

### CODE REVIEW

**Comment by jsamouh** [comment]
@mnapoli not sure to understand why phpunit failed with my change

**Comment by mnapoli** [comment]
Thanks!

I have no idea about the tests 🤔 the error is weird. I've tried restarting it.

Do you have any idea how bigger the generated files are? If you don't I will have to compile it locally and see the difference for myself (the goal is to keep PHP layers as slim as possible because there isn't much space on Lambda)

**Comment by jsamouh** [comment]
@mnapoli 

-rwxrwxrwx 1 root root 700 Apr  2 07:54 console.zip
-rwxrwxrwx 1 root root 24M Apr  2 07:55 php-72.zip
-rwxrwxrwx 1 root root 31M Apr  2 07:55 php-72-fpm.zip
-rwxrwxrwx 1 root root 24M Apr  2 07:55 php-73.zip
-rwxrwxrwx 1 root root 31M Apr  2 07:55 php-73-fpm.zip

**Comment by mnapoli** [comment]
I understand about the tests now, your fork is lagging behind master. It's fine for the merge though.

Thank you @jsamouh for providing the numbers, that sounds OK! I'll merge and give it a try locally.

**Comment by mnapoli** [comment]
Oh no I understand you did the PR against the 0.3 branch, not master. I should delete this branch to avoid confusion.

**Comment by jsamouh** [comment]
Yeah for me it was a 0.3 feature, because we want this feature in this branch. 
And I thought you will merge 0.3 into master. It is not the case ?

**Comment by mnapoli** [comment]
0.3 is master now (the existing `0.3` branch is a leftover from a few months ago). It's all good I merged manually.

**Comment by mnapoli** [comment]
New runtimes include SOAP by default!

**Pull request merged**
